In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('stud.csv')

In [5]:
df.head()

gender race_ethnicity parental_level_of_education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test_preparation_course  math_score  reading_score  writing_score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [8]:
df.shape

(1000, 8)

In [11]:
df.isna().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [13]:
df.duplicated().sum()

0

In [16]:
# Check Null and Dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64 
 6   reading_score                1000 non-null   int64 
 7   writing_score                1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB


In [20]:
df['gender'].unique()

array(['female', 'male'], dtype=object)

In [21]:
df.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     81
reading_score                  72
writing_score                  77
dtype: int64

In [22]:
df['total score'] = df['math_score'] + df['reading_score'] + df['writing_score']
df['average'] = df['total score']/3

In [23]:
reading_full = df[df['reading_score'] == 100]['average'].count()
writing_full = df[df['writing_score'] == 100]['average'].count()
math_full = df[df['math_score'] == 100]['average'].count()

print(f'Number of students with full marks in Maths: {math_full}')
print(f'Number of students with full marks in Writing: {writing_full}')
print(f'Number of students with full marks in Reading: {reading_full}')

Number of students with full marks in Maths: 7
Number of students with full marks in Writing: 14
Number of students with full marks in Reading: 17


In [33]:
reading_full = df[df['reading_score'] == 100]['reading_score'].count()
writing_full = df[df['writing_score'] == 100]['writing_score'].count()
math_full = df[df['math_score'] == 100]['math_score'].count()

print(f'Number of students with full marks in Maths: {math_full}')
print(f'Number of students with full marks in Writing: {writing_full}')
print(f'Number of students with full marks in Reading: {reading_full}')

Number of students with full marks in Maths: 7
Number of students with full marks in Writing: 14
Number of students with full marks in Reading: 17


In [4]:
t= np.arange( 0,5*np.pi, 0.1)
t

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9,
       11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15

In [23]:
df.iloc[4 5 1 3 0 8 2 9 7 6]

SyntaxError: invalid syntax (3684395795.py, line 1)

In [62]:
u=np.array([3, 5, 5,6 ,6])
type(u)
u

array([3, 5, 5, 6, 6])

In [67]:
x=np.random.permutation(10)
type(x)
print(x)
x

[6 1 9 8 3 5 0 4 7 2]


array([6, 1, 9, 8, 3, 5, 0, 4, 7, 2])

In [54]:
def split(data, ratio):
    shuffled = np.random.permutation(len(data))
    test_set_size = int( len(data)* ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    
    train_set = data.iloc[train_indices]
    test_set = data.iloc[test_indices]

    return train_indices, test_indices

In [44]:
type(df)

pandas.core.frame.DataFrame

In [45]:
x_train,y_test = split(df, 0.2)

In [52]:
x_train

array([558, 682, 367,  50, 997, 424, 725, 839,   1, 457, 229, 605, 140,
       753, 450, 492, 303, 339, 663, 697, 509, 837, 967, 626, 329, 613,
       606,  36, 969,  63, 910, 742, 316, 751,  22, 352, 720, 599, 427,
       157, 429, 199, 575, 198, 693, 502, 445, 545, 111, 287, 920, 862,
       793, 368,   5, 803, 431, 534, 419, 278, 248, 136, 807, 348, 121,
       186, 702, 617, 637, 831, 206, 727, 914, 163, 881, 600, 440, 107,
       763, 937, 284, 452, 410, 397, 849, 459, 311,  45, 739, 203, 131,
       843, 116, 806, 123, 106, 337, 379, 585, 632,  41, 651, 103,  88,
       500, 676, 472, 137, 247, 817, 465,  60, 827, 342, 765, 628, 643,
       321, 295, 544, 829, 176, 811, 790, 587, 455, 201, 927, 959, 798,
       766, 756, 722, 808, 212, 721, 100, 731,  53, 571, 960, 944, 508,
       936, 543, 916, 302, 441,  99, 399, 863, 772, 428,  33, 211, 630,
       375, 541, 889, 326, 805, 883, 146, 372, 546, 293, 467, 418, 351,
       487, 495, 638, 900,  52, 698, 625, 815, 411, 597, 764, 95

In [51]:
type(x_train)

numpy.ndarray

In [49]:
train_set = df.iloc[x_train]

In [50]:
train_set

gender race_ethnicity parental_level_of_education         lunch  \
558  female        group B          associate's degree  free/reduced   
682    male        group B                 high school      standard   
367    male        group C           bachelor's degree  free/reduced   
50     male        group E                some college      standard   
997  female        group C                 high school  free/reduced   
..      ...            ...                         ...           ...   
647  female        group E                 high school  free/reduced   
874  female        group C           bachelor's degree  free/reduced   
497  female        group D                some college  free/reduced   
437    male        group D          associate's degree  free/reduced   
797  female        group E          associate's degree  free/reduced   

    test_preparation_course  math_score  reading_score  writing_score  
558                    none          53             70             70  
682                    none          62             55             54  
367                    none          61             66             61  
50                     none          53             55             48  
997               completed          59             71             65  
..                      ...         ...            ...            ...  
647                    none          64             62             68  
874                    none          43             62             61  
497               completed          59             78             76  
437                    none          75             66             73  
797                    none          70             84             81  

[800 rows x 8 columns]